{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "acl-core",
    "version": "1.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "acl-core-1.1.0-SNAPSHOT.jar",
          "url": "acl-core-1.1.0-SNAPSHOT.jar",
          "size": 21328,
          "sha512": "f44e6af1dba813cc043319a15a89b183a3d82287ff07fdf2ad60206e86b3f6fba432b71381e4a83ff65216b12dae53b9245e31ec88e796d24ff46d490416bd35",
          "sha256": "fc6498e05f9c65a34ed955e8845f1514d0ff98d0e9a9913b7bb07e61d5439adf",
          "sha1": "d34b936cb9d5ecf840dbf7d39f10b44689cd73d8",
          "md5": "0ed8d0159c00c5558a4785a34c17472e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-loom",
          "version": {
            "requires": "1.4-SNAPSHOT"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.1.3-jre"
          }
        },
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.24"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "architectury-plugin",
          "module": "architectury-plugin.gradle.plugin",
          "version": {
            "requires": "3.4-SNAPSHOT"
          }
        },
        {
          "group": "com.github.johnrengelman",
          "module": "shadow",
          "version": {
            "requires": "8.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "acl-core-1.1.0-SNAPSHOT.jar",
          "url": "acl-core-1.1.0-SNAPSHOT.jar",
          "size": 21328,
          "sha512": "f44e6af1dba813cc043319a15a89b183a3d82287ff07fdf2ad60206e86b3f6fba432b71381e4a83ff65216b12dae53b9245e31ec88e796d24ff46d490416bd35",
          "sha256": "fc6498e05f9c65a34ed955e8845f1514d0ff98d0e9a9913b7bb07e61d5439adf",
          "sha1": "d34b936cb9d5ecf840dbf7d39f10b44689cd73d8",
          "md5": "0ed8d0159c00c5558a4785a34c17472e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "acl-core-1.1.0-SNAPSHOT-sources.jar",
          "url": "acl-core-1.1.0-SNAPSHOT-sources.jar",
          "size": 12048,
          "sha512": "17afc77b95178481423a3b6e282b4e55b6c1f2eec011514b5c5535821073511e80f5741dcaf52e0f0e606019a56ae86adb1ff52b9f08a09ee59e6f6ec68e2ff9",
          "sha256": "70689314dbd105279ffea494a97924f60b45664ade3706543a36a52301fb6dbd",
          "sha1": "955f79c3432520cd15e5bccb0384959a4960823a",
          "md5": "74949754b823d80f78eac52d85662b9e"
        }
      ]
    }
  ]
}
