{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "acl",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "acl-1.2.1.jar",
          "url": "acl-1.2.1.jar",
          "size": 34323,
          "sha512": "3b9c58b0e2593c073a0d07232e8ed78d42cc295aeb7167db654b266e04e018655cebdb5077868af1d4436c2688eb987c956c3fcf444a4222be2ea0ef0aa6c008",
          "sha256": "cd8410df162bdd6b407ebdd53fb158a2fe8ff23f980e7d559033ba2681216f66",
          "sha1": "e8e86b32392968bce08f5e7a10276759b0d31c90",
          "md5": "4001102091d9977e6dc1ef279aa4ecf7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-loom",
          "version": {
            "requires": "1.4-SNAPSHOT"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.1.3-jre"
          }
        },
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.25"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "architectury-plugin",
          "module": "architectury-plugin.gradle.plugin",
          "version": {
            "requires": "3.4-SNAPSHOT"
          }
        },
        {
          "group": "com.github.johnrengelman",
          "module": "shadow",
          "version": {
            "requires": "8.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "acl-1.2.1.jar",
          "url": "acl-1.2.1.jar",
          "size": 34323,
          "sha512": "3b9c58b0e2593c073a0d07232e8ed78d42cc295aeb7167db654b266e04e018655cebdb5077868af1d4436c2688eb987c956c3fcf444a4222be2ea0ef0aa6c008",
          "sha256": "cd8410df162bdd6b407ebdd53fb158a2fe8ff23f980e7d559033ba2681216f66",
          "sha1": "e8e86b32392968bce08f5e7a10276759b0d31c90",
          "md5": "4001102091d9977e6dc1ef279aa4ecf7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "acl-1.2.1-sources.jar",
          "url": "acl-1.2.1-sources.jar",
          "size": 16657,
          "sha512": "9e2edf49d38dc28ceb9cb65e780f192dfed0cf75257cd972377376532b078b392260eb4f77a868de6d499d06a18421462e120677f53c7576023a0a039b4f919a",
          "sha256": "404dc466528ba811c6cc7bf74ad0c79b5b6f342e13da54c5755318366dfd59f0",
          "sha1": "1259b84e75562c480aa708fa61ec57e060732a77",
          "md5": "362faecf2ba1d980bcc47ba61eba9b6c"
        }
      ]
    }
  ]
}
