{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "acl-core",
    "version": "1.0.96-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "acl-core-1.0.96-SNAPSHOT.jar",
          "url": "acl-core-1.0.96-SNAPSHOT.jar",
          "size": 21639,
          "sha512": "be8060745a5841ca4c3522f474a570f63bbd3c78f70b5f1621838365b28d4bff1346004ea31eff8c02ac0f5a13237e39b75a8977b247023a07606624e84aa16e",
          "sha256": "cbf2442d9c1b0e0584c2fb72d1706f83fa4c39079c3d7aab43dc2accd57a2d23",
          "sha1": "238096774ada3b8e57cdd7e90b55ec5fe7e5d93b",
          "md5": "a2d5caa025d19efb4573e8627c2c695f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-loom",
          "version": {
            "requires": "1.4-SNAPSHOT"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.1.3-jre"
          }
        },
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.24"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "architectury-plugin",
          "module": "architectury-plugin.gradle.plugin",
          "version": {
            "requires": "3.4-SNAPSHOT"
          }
        },
        {
          "group": "com.github.johnrengelman",
          "module": "shadow",
          "version": {
            "requires": "8.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "acl-core-1.0.96-SNAPSHOT.jar",
          "url": "acl-core-1.0.96-SNAPSHOT.jar",
          "size": 21639,
          "sha512": "be8060745a5841ca4c3522f474a570f63bbd3c78f70b5f1621838365b28d4bff1346004ea31eff8c02ac0f5a13237e39b75a8977b247023a07606624e84aa16e",
          "sha256": "cbf2442d9c1b0e0584c2fb72d1706f83fa4c39079c3d7aab43dc2accd57a2d23",
          "sha1": "238096774ada3b8e57cdd7e90b55ec5fe7e5d93b",
          "md5": "a2d5caa025d19efb4573e8627c2c695f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "acl-core-1.0.96-SNAPSHOT-sources.jar",
          "url": "acl-core-1.0.96-SNAPSHOT-sources.jar",
          "size": 12039,
          "sha512": "e26678d9f04821726e69ed979b3211aa81b6f44531680a528cd7761c6a02df2469e031e6c2303a421e2a56b6cce39cdc2146262d134249b02eb3bb77a7a7cda7",
          "sha256": "802f93b65efd67767e02cb04234f1e3f2c01bf45508be424f0dbb786f54d1d7b",
          "sha1": "c1008392de41a6486eb7fccc3154fcf7e4c8bf3e",
          "md5": "cad2894a4c9d4d6959f0ecdb22bda768"
        }
      ]
    }
  ]
}
