{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "acl-core",
    "version": "1.0.99-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "acl-core-1.0.99-SNAPSHOT.jar",
          "url": "acl-core-1.0.99-SNAPSHOT.jar",
          "size": 21307,
          "sha512": "2a534c6266a729cc3a41319d887536c6d41c3ba7ec9cd4057d74196336776395d300eb3dcbccb28136a1d26b318fc3ca3c443c6a66e067d77ff17e81b1de7723",
          "sha256": "75682fb19d1f5f7a74685342901c378fc9f06a188447f793ef8af8f50fceaedf",
          "sha1": "5eb1ae724b3fc3cda8d63545defd25312faf0449",
          "md5": "e8c0a054833eb270ec2c3334675a4a7e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-loom",
          "version": {
            "requires": "1.4-SNAPSHOT"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.1.3-jre"
          }
        },
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.24"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "architectury-plugin",
          "module": "architectury-plugin.gradle.plugin",
          "version": {
            "requires": "3.4-SNAPSHOT"
          }
        },
        {
          "group": "com.github.johnrengelman",
          "module": "shadow",
          "version": {
            "requires": "8.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "acl-core-1.0.99-SNAPSHOT.jar",
          "url": "acl-core-1.0.99-SNAPSHOT.jar",
          "size": 21307,
          "sha512": "2a534c6266a729cc3a41319d887536c6d41c3ba7ec9cd4057d74196336776395d300eb3dcbccb28136a1d26b318fc3ca3c443c6a66e067d77ff17e81b1de7723",
          "sha256": "75682fb19d1f5f7a74685342901c378fc9f06a188447f793ef8af8f50fceaedf",
          "sha1": "5eb1ae724b3fc3cda8d63545defd25312faf0449",
          "md5": "e8c0a054833eb270ec2c3334675a4a7e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "acl-core-1.0.99-SNAPSHOT-sources.jar",
          "url": "acl-core-1.0.99-SNAPSHOT-sources.jar",
          "size": 12045,
          "sha512": "23fbfe397bf3176ca8948f422a0b8025310a9b9fd579a85dd673c50203e8ebef9246b75f0fae665cd6323876cce443e860ba88460acb328d641fa44a7015d77d",
          "sha256": "1ea8e9fd7b51d4829bd5f56866f55e6b234c432ce30cfb4025bc03ce96365f45",
          "sha1": "ee27f623821bb909f7acf2c26e3e8285a3b05e9c",
          "md5": "9dec51e14d7cece786dbaa6ac4719c00"
        }
      ]
    }
  ]
}
