{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "acl-core",
    "version": "1.1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "acl-core-1.1.1-SNAPSHOT.jar",
          "url": "acl-core-1.1.1-SNAPSHOT.jar",
          "size": 21325,
          "sha512": "a2fb3ff9bd35337935dd80b87fbe60c11c8b5eca395c0d1cd21fc29b43762bc9cd9b023b8d3cef762c3ff986b1a02c51c03b233c4b864a5b2ccaa90610fee902",
          "sha256": "ddb6c0e69ab5af8f5ba9334404348adb047f8d9d8c23e6149c53f24ed62ec905",
          "sha1": "c7e5043b1a78b41e67a9b84afcc8777eaea5e177",
          "md5": "e1d905ee0f2c2458166b674c586067e6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-loom",
          "version": {
            "requires": "1.4-SNAPSHOT"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.1.3-jre"
          }
        },
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.24"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "architectury-plugin",
          "module": "architectury-plugin.gradle.plugin",
          "version": {
            "requires": "3.4-SNAPSHOT"
          }
        },
        {
          "group": "com.github.johnrengelman",
          "module": "shadow",
          "version": {
            "requires": "8.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "acl-core-1.1.1-SNAPSHOT.jar",
          "url": "acl-core-1.1.1-SNAPSHOT.jar",
          "size": 21325,
          "sha512": "a2fb3ff9bd35337935dd80b87fbe60c11c8b5eca395c0d1cd21fc29b43762bc9cd9b023b8d3cef762c3ff986b1a02c51c03b233c4b864a5b2ccaa90610fee902",
          "sha256": "ddb6c0e69ab5af8f5ba9334404348adb047f8d9d8c23e6149c53f24ed62ec905",
          "sha1": "c7e5043b1a78b41e67a9b84afcc8777eaea5e177",
          "md5": "e1d905ee0f2c2458166b674c586067e6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "acl-core-1.1.1-SNAPSHOT-sources.jar",
          "url": "acl-core-1.1.1-SNAPSHOT-sources.jar",
          "size": 12045,
          "sha512": "652265a2c161d40b7e2ff4059b6fbafb99fd97aa176a156234b643563305d4b4d06b7e81c50f74f3f0dec1db925bc2777365c0e68d8b2732d54f7f1d696f722e",
          "sha256": "7225e19113caba99743ca1ded36d97bfc75a0da67e0f8e0f692148e6b7c171d5",
          "sha1": "6b17405ff87a8ba5bfe182aa093ebc97d697de74",
          "md5": "b1a8bbea2d5f8831628acd3f1a93f164"
        }
      ]
    }
  ]
}
