{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "acl-core",
    "version": "1.0.95-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "acl-core-1.0.95-SNAPSHOT.jar",
          "url": "acl-core-1.0.95-SNAPSHOT.jar",
          "size": 21656,
          "sha512": "8cd21f0eb8b926dd49a4a77408799012608acb5c30ce8ccba601aed40c3234a34373dfde06b172dd584b820024a88df3ee6aea787da6e3e14f700ef8b587bbcf",
          "sha256": "1d1d217052ceed91b5bb6beef0846c59901a61482aad59cf6b09ccbb86bb964f",
          "sha1": "53d95323ba4304cdfe1cb124f64b07fcfffbd4be",
          "md5": "9effe80af8c9de12cbf4e7c639b319b2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-loom",
          "version": {
            "requires": "1.4-SNAPSHOT"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.1.3-jre"
          }
        },
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.24"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "architectury-plugin",
          "module": "architectury-plugin.gradle.plugin",
          "version": {
            "requires": "3.4-SNAPSHOT"
          }
        },
        {
          "group": "com.github.johnrengelman",
          "module": "shadow",
          "version": {
            "requires": "8.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "acl-core-1.0.95-SNAPSHOT.jar",
          "url": "acl-core-1.0.95-SNAPSHOT.jar",
          "size": 21656,
          "sha512": "8cd21f0eb8b926dd49a4a77408799012608acb5c30ce8ccba601aed40c3234a34373dfde06b172dd584b820024a88df3ee6aea787da6e3e14f700ef8b587bbcf",
          "sha256": "1d1d217052ceed91b5bb6beef0846c59901a61482aad59cf6b09ccbb86bb964f",
          "sha1": "53d95323ba4304cdfe1cb124f64b07fcfffbd4be",
          "md5": "9effe80af8c9de12cbf4e7c639b319b2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "acl-core-1.0.95-SNAPSHOT-sources.jar",
          "url": "acl-core-1.0.95-SNAPSHOT-sources.jar",
          "size": 12041,
          "sha512": "5e3ac2c6c8187470cffcac9d75ee7650a7d78b014825eeb281dbb1060250ccc574398dacc91d711818fe0058a09c2fafc5a1e75f0aa46a43cd4ff7be4727c046",
          "sha256": "918d8267ae09794a1af70f2b4229d3e9c7579264696a534958560eaccb2d01d8",
          "sha1": "7f72612e92a34d30ff23ef8714a9f9d4cee8547e",
          "md5": "caa54e7773a2a67f8449f779c91d3803"
        }
      ]
    }
  ]
}
