{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "acl",
    "version": "1.1.17-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "acl-1.1.17-SNAPSHOT.jar",
          "url": "acl-1.1.17-SNAPSHOT.jar",
          "size": 28364,
          "sha512": "e652a98b2618fbf669e317766de8da8c3431d9661b7668f58e6217d1e7f951a5a0a2e79cb7473d54bb9d7217a011d117a0d7f1077c35b5218e9ebcc98ce8826c",
          "sha256": "94708868788c828a99177cc4fe3e8e1999dccbe5ceeac2210a9bb01a74544c7d",
          "sha1": "b2a85357521d3f85c4e143667b4ad0c7b4ce8a7b",
          "md5": "30a2315d3c0e946a50c1d04f1247d4bb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-loom",
          "version": {
            "requires": "1.4-SNAPSHOT"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.1.3-jre"
          }
        },
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.24"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "architectury-plugin",
          "module": "architectury-plugin.gradle.plugin",
          "version": {
            "requires": "3.4-SNAPSHOT"
          }
        },
        {
          "group": "com.github.johnrengelman",
          "module": "shadow",
          "version": {
            "requires": "8.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "acl-1.1.17-SNAPSHOT.jar",
          "url": "acl-1.1.17-SNAPSHOT.jar",
          "size": 28364,
          "sha512": "e652a98b2618fbf669e317766de8da8c3431d9661b7668f58e6217d1e7f951a5a0a2e79cb7473d54bb9d7217a011d117a0d7f1077c35b5218e9ebcc98ce8826c",
          "sha256": "94708868788c828a99177cc4fe3e8e1999dccbe5ceeac2210a9bb01a74544c7d",
          "sha1": "b2a85357521d3f85c4e143667b4ad0c7b4ce8a7b",
          "md5": "30a2315d3c0e946a50c1d04f1247d4bb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "acl-1.1.17-SNAPSHOT-sources.jar",
          "url": "acl-1.1.17-SNAPSHOT-sources.jar",
          "size": 13417,
          "sha512": "224857b3c6d361d4af1f8de4c946802366d6f317648494e7eea65f816909c43112cdf0f11a2cd132c8c98fa1d982d5269fc54c6bbd0ec7243517a757f59f2766",
          "sha256": "7538977ea4d0db02d3132636445cf2cdb38ea8d1db801d137d37c7b9b850e29c",
          "sha1": "ffc72a083d2733ba7ad34eebd0dbb2426b6b933a",
          "md5": "7f0b72243d3f12e4fb5fb8a07600ff39"
        }
      ]
    }
  ]
}
