{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "acl",
    "version": "1.1.14-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "acl-1.1.14-SNAPSHOT.jar",
          "url": "acl-1.1.14-SNAPSHOT.jar",
          "size": 26761,
          "sha512": "345359f1ac609f1b472038a8da498f3e77ab6532f936439afa92dc097557275b73cf5cdf6e6a90f2b28b010fa97157b9c3be1154a6f29f2b82a450be355180b0",
          "sha256": "081660de0461990b8448ae65602c6090067727d7217fe1f7e1733acd63d3bbc7",
          "sha1": "745464f42e6875fbc6b965f7dd0b5aa004df0f5d",
          "md5": "8331f56fc1140e8f64a0b01ddb764bdb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-loom",
          "version": {
            "requires": "1.4-SNAPSHOT"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.1.3-jre"
          }
        },
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.24"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "architectury-plugin",
          "module": "architectury-plugin.gradle.plugin",
          "version": {
            "requires": "3.4-SNAPSHOT"
          }
        },
        {
          "group": "com.github.johnrengelman",
          "module": "shadow",
          "version": {
            "requires": "8.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "acl-1.1.14-SNAPSHOT.jar",
          "url": "acl-1.1.14-SNAPSHOT.jar",
          "size": 26761,
          "sha512": "345359f1ac609f1b472038a8da498f3e77ab6532f936439afa92dc097557275b73cf5cdf6e6a90f2b28b010fa97157b9c3be1154a6f29f2b82a450be355180b0",
          "sha256": "081660de0461990b8448ae65602c6090067727d7217fe1f7e1733acd63d3bbc7",
          "sha1": "745464f42e6875fbc6b965f7dd0b5aa004df0f5d",
          "md5": "8331f56fc1140e8f64a0b01ddb764bdb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "acl-1.1.14-SNAPSHOT-sources.jar",
          "url": "acl-1.1.14-SNAPSHOT-sources.jar",
          "size": 13559,
          "sha512": "803c9c43711bd1b7384dfb408258d5aa2e05702c135263c4ce2f89056056bea5a5872b73b48d3fe0d9d9c2b0e56689f1171b000a80482dddc4db2e4896fb3d5e",
          "sha256": "92f917b0db9ba7eb92a9b9965bb91b03f89e7fcb97f59ee14333a71f8c79b297",
          "sha1": "e0d1417375b83b8d241a80528690b6e40a9f019d",
          "md5": "438c07b5d15e735ffd9259dac2d759ed"
        }
      ]
    }
  ]
}
