{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "acl",
    "version": "1.1.14-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "acl-1.1.14-SNAPSHOT.jar",
          "url": "acl-1.1.14-SNAPSHOT.jar",
          "size": 26047,
          "sha512": "27e899fd6f1bde79f2dce74b21cd1b984f92f87d8234cb501fdc039a2de96f77344b9faf26de6ee9203e9e5eb75b1d5df477032ae91d70336719fbee14109e0c",
          "sha256": "77ce6f30556a6a0edc1649122aa0a4e99679c2b2eaf0fe321f3e6a0c720c6d46",
          "sha1": "d84847822fbd301dfabddd8e9958fe683336aef2",
          "md5": "a2157818114856c272a02a9a6379d2c9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-loom",
          "version": {
            "requires": "1.4-SNAPSHOT"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.1.3-jre"
          }
        },
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.24"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "architectury-plugin",
          "module": "architectury-plugin.gradle.plugin",
          "version": {
            "requires": "3.4-SNAPSHOT"
          }
        },
        {
          "group": "com.github.johnrengelman",
          "module": "shadow",
          "version": {
            "requires": "8.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "acl-1.1.14-SNAPSHOT.jar",
          "url": "acl-1.1.14-SNAPSHOT.jar",
          "size": 26047,
          "sha512": "27e899fd6f1bde79f2dce74b21cd1b984f92f87d8234cb501fdc039a2de96f77344b9faf26de6ee9203e9e5eb75b1d5df477032ae91d70336719fbee14109e0c",
          "sha256": "77ce6f30556a6a0edc1649122aa0a4e99679c2b2eaf0fe321f3e6a0c720c6d46",
          "sha1": "d84847822fbd301dfabddd8e9958fe683336aef2",
          "md5": "a2157818114856c272a02a9a6379d2c9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "acl-1.1.14-SNAPSHOT-sources.jar",
          "url": "acl-1.1.14-SNAPSHOT-sources.jar",
          "size": 13468,
          "sha512": "95e77c409709e231b0db758e0f65e07e90aa0f006f4a11b4c9b94081d7a853e40e535c3558b0d711f1ffe22b18e222ef1c4fea65c134aec2e63fba0782c10132",
          "sha256": "a8ae5b702d7afa2e339be68bace26e738a72ef949a59e1e89f608351d887e778",
          "sha1": "130d90392cd5e609a58518b19002c20258ea76ce",
          "md5": "44cbc984bbcbc5afe8bf44685b14e8d4"
        }
      ]
    }
  ]
}
