{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "acl-core",
    "version": "1.0.97-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "acl-core-1.0.97-SNAPSHOT.jar",
          "url": "acl-core-1.0.97-SNAPSHOT.jar",
          "size": 21397,
          "sha512": "fd43ef2064d5476b7a42d9adbf782932cad3cfef4fcebb025d7b54be0b9226fe87c44dfb26b845b399d698d78b1273c468e77ce24d02ccebeb75de3f80ee7224",
          "sha256": "a74d840b3c4f2c93f131919094e1eba59cd408848ae98be67928fc2b0553edea",
          "sha1": "496f06c5101def8d8fa7822da6d3bc4a800ea3c0",
          "md5": "bd4499d4c08573190a002f86809ab04c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-loom",
          "version": {
            "requires": "1.4-SNAPSHOT"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.1.3-jre"
          }
        },
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.24"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "architectury-plugin",
          "module": "architectury-plugin.gradle.plugin",
          "version": {
            "requires": "3.4-SNAPSHOT"
          }
        },
        {
          "group": "com.github.johnrengelman",
          "module": "shadow",
          "version": {
            "requires": "8.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "acl-core-1.0.97-SNAPSHOT.jar",
          "url": "acl-core-1.0.97-SNAPSHOT.jar",
          "size": 21397,
          "sha512": "fd43ef2064d5476b7a42d9adbf782932cad3cfef4fcebb025d7b54be0b9226fe87c44dfb26b845b399d698d78b1273c468e77ce24d02ccebeb75de3f80ee7224",
          "sha256": "a74d840b3c4f2c93f131919094e1eba59cd408848ae98be67928fc2b0553edea",
          "sha1": "496f06c5101def8d8fa7822da6d3bc4a800ea3c0",
          "md5": "bd4499d4c08573190a002f86809ab04c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "acl-core-1.0.97-SNAPSHOT-sources.jar",
          "url": "acl-core-1.0.97-SNAPSHOT-sources.jar",
          "size": 12050,
          "sha512": "ab84c375f3bacf6cb982ec57a221d17f899be02e5f5842bf607d3e60ae6eda602f077387b6671113359805428e436bfe7a388443968ade4e11020cbcfdd67e6a",
          "sha256": "680b5a9de95bfa4b1a272fb45316db626b18dd9f2695df608690d9033da61d17",
          "sha1": "fb7f6b28560d92a72b975446137e28c14cdea711",
          "md5": "06a1a6ffe948a2c4f03b7177a4ba0309"
        }
      ]
    }
  ]
}
