{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "acl-core",
    "version": "1.1.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "acl-core-1.1.5-SNAPSHOT.jar",
          "url": "acl-core-1.1.5-SNAPSHOT.jar",
          "size": 24037,
          "sha512": "698f4b18fa882216b0cff154174eaea4ab3108152fd9b5292b34c69b847e6cf6a890a8ce70bc3034d06f53c597aedac342b3de34d097ec9d11c59c4d9fa74735",
          "sha256": "52b86328f5edea5fc176d5420e5c0b51216442eff8c45d1c426c87e2a7e12fae",
          "sha1": "c92a541250bb5e20ba3afb6f80be175648870b3a",
          "md5": "c66379b9b4563024dcad7dcfc5901c56"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-loom",
          "version": {
            "requires": "1.4-SNAPSHOT"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.1.3-jre"
          }
        },
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.24"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "architectury-plugin",
          "module": "architectury-plugin.gradle.plugin",
          "version": {
            "requires": "3.4-SNAPSHOT"
          }
        },
        {
          "group": "com.github.johnrengelman",
          "module": "shadow",
          "version": {
            "requires": "8.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "acl-core-1.1.5-SNAPSHOT.jar",
          "url": "acl-core-1.1.5-SNAPSHOT.jar",
          "size": 24037,
          "sha512": "698f4b18fa882216b0cff154174eaea4ab3108152fd9b5292b34c69b847e6cf6a890a8ce70bc3034d06f53c597aedac342b3de34d097ec9d11c59c4d9fa74735",
          "sha256": "52b86328f5edea5fc176d5420e5c0b51216442eff8c45d1c426c87e2a7e12fae",
          "sha1": "c92a541250bb5e20ba3afb6f80be175648870b3a",
          "md5": "c66379b9b4563024dcad7dcfc5901c56"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "acl-core-1.1.5-SNAPSHOT-sources.jar",
          "url": "acl-core-1.1.5-SNAPSHOT-sources.jar",
          "size": 12727,
          "sha512": "fe06703a449b65bccd3b9f6f09d5197c2a6f6cbbab7487d32e38c7c942d1749750c5d983fc50d60e02f5bc4e4474715c44e180fa7dead0999694bea438d34e03",
          "sha256": "bf5eee406190f19bd1ffd1658c04ae83fbbbea9263fab6db6c1f96e860a6a2c2",
          "sha1": "113605b903e5243360c3d6b98061580b5ef126e9",
          "md5": "0a765fe8a0ec2e2d77d4382774d666de"
        }
      ]
    }
  ]
}
