{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "acl",
    "version": "1.1.10-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "acl-1.1.10-SNAPSHOT.jar",
          "url": "acl-1.1.10-SNAPSHOT.jar",
          "size": 25957,
          "sha512": "d092dee9abda271d94a7df0ee5c33a9697c5005e3157089350087f9ef3eca2d98da1c6b1e64c33b399bd4a1d2c6a8d4b0c9fbb871ff6739d780e960f1f332106",
          "sha256": "207c677d4540ceee527f4adb51fcfcd45336e1a8fc005069a9d91c56b2989dd7",
          "sha1": "81c308d823714791fa0dacf3f7a65c7a812551f2",
          "md5": "3e32b1e522649b29c9a61467858dcd2b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-loom",
          "version": {
            "requires": "1.4-SNAPSHOT"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.1.3-jre"
          }
        },
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.24"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "architectury-plugin",
          "module": "architectury-plugin.gradle.plugin",
          "version": {
            "requires": "3.4-SNAPSHOT"
          }
        },
        {
          "group": "com.github.johnrengelman",
          "module": "shadow",
          "version": {
            "requires": "8.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "acl-1.1.10-SNAPSHOT.jar",
          "url": "acl-1.1.10-SNAPSHOT.jar",
          "size": 25957,
          "sha512": "d092dee9abda271d94a7df0ee5c33a9697c5005e3157089350087f9ef3eca2d98da1c6b1e64c33b399bd4a1d2c6a8d4b0c9fbb871ff6739d780e960f1f332106",
          "sha256": "207c677d4540ceee527f4adb51fcfcd45336e1a8fc005069a9d91c56b2989dd7",
          "sha1": "81c308d823714791fa0dacf3f7a65c7a812551f2",
          "md5": "3e32b1e522649b29c9a61467858dcd2b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "acl-1.1.10-SNAPSHOT-sources.jar",
          "url": "acl-1.1.10-SNAPSHOT-sources.jar",
          "size": 13328,
          "sha512": "db32041d9f0cad7f4acb2adcc8ad5177d2e9d583b36d0d5ad2d8621aec53c9e31e48b91847359c2033dd78998273982b09b28f386f9bfe539a9141cf4d3fef26",
          "sha256": "cc05c2537dbc6d192445fc8593158a5763e3368af4b8435f22b5dda863d50d46",
          "sha1": "0f0dd6daeddbee200ddd3f192741c7d7792a2bda",
          "md5": "d23f78977bbaae020dcc74b89a90f133"
        }
      ]
    }
  ]
}
