{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "acl-core",
    "version": "1.1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "acl-core-1.1.2-SNAPSHOT.jar",
          "url": "acl-core-1.1.2-SNAPSHOT.jar",
          "size": 22427,
          "sha512": "c412acbd541b8a053cd11881612520fca0f508153c54e32cef6e24f33828e313936ad5077f6d5b0b8acfe0c7f060bb087d2855e6e393fe68eaf4c07653f7400c",
          "sha256": "271e1795d8a04e733c2747d04ceb049bb4d8f3a4edb467f67a549d49746b5495",
          "sha1": "805ce7890e44fe2807ac27b5c7ef7e7425354f41",
          "md5": "618701e4556b572611bfb47ce126ba00"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-loom",
          "version": {
            "requires": "1.4-SNAPSHOT"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.1.3-jre"
          }
        },
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.24"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "architectury-plugin",
          "module": "architectury-plugin.gradle.plugin",
          "version": {
            "requires": "3.4-SNAPSHOT"
          }
        },
        {
          "group": "com.github.johnrengelman",
          "module": "shadow",
          "version": {
            "requires": "8.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "acl-core-1.1.2-SNAPSHOT.jar",
          "url": "acl-core-1.1.2-SNAPSHOT.jar",
          "size": 22427,
          "sha512": "c412acbd541b8a053cd11881612520fca0f508153c54e32cef6e24f33828e313936ad5077f6d5b0b8acfe0c7f060bb087d2855e6e393fe68eaf4c07653f7400c",
          "sha256": "271e1795d8a04e733c2747d04ceb049bb4d8f3a4edb467f67a549d49746b5495",
          "sha1": "805ce7890e44fe2807ac27b5c7ef7e7425354f41",
          "md5": "618701e4556b572611bfb47ce126ba00"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "acl-core-1.1.2-SNAPSHOT-sources.jar",
          "url": "acl-core-1.1.2-SNAPSHOT-sources.jar",
          "size": 12563,
          "sha512": "3a498bdd3eb632fa7f8c4bc474ebe6a8caaaba188e51e3cdc61fa4fed5cae1fe052b9c8dad0e92a805cd68157a8ce24af6ee88b9cb9d9322257a3f3fc4553e8c",
          "sha256": "4258dd7d83f55807d20b5dd640e96858004f034045f85a73fb0fa6367566e696",
          "sha1": "3ae27712c771a28db51f1604d2bb3584e7570aa4",
          "md5": "09afc4db03030296dc9aea3f24ef753f"
        }
      ]
    }
  ]
}
