{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "acl",
    "version": "1.1.11-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "acl-1.1.11-SNAPSHOT.jar",
          "url": "acl-1.1.11-SNAPSHOT.jar",
          "size": 25682,
          "sha512": "736480c1ad2a916fb1c2d64fc234c724812bba288c37970e400c2ba8ad3c8b3583e229da078bff53123385efb55d4b4555b59cb5dd758747c1b9ba2f18e348db",
          "sha256": "73b9e5076dbdea69dbce55b91f47bf492d0cfc7f586ca92b9342463ad14f943e",
          "sha1": "08f7045161cada2ede809e41a4db0f4752b2b146",
          "md5": "4c2928b9acbf3053fa357b7a3e7e2310"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-loom",
          "version": {
            "requires": "1.4-SNAPSHOT"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.1.3-jre"
          }
        },
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.24"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "architectury-plugin",
          "module": "architectury-plugin.gradle.plugin",
          "version": {
            "requires": "3.4-SNAPSHOT"
          }
        },
        {
          "group": "com.github.johnrengelman",
          "module": "shadow",
          "version": {
            "requires": "8.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "acl-1.1.11-SNAPSHOT.jar",
          "url": "acl-1.1.11-SNAPSHOT.jar",
          "size": 25682,
          "sha512": "736480c1ad2a916fb1c2d64fc234c724812bba288c37970e400c2ba8ad3c8b3583e229da078bff53123385efb55d4b4555b59cb5dd758747c1b9ba2f18e348db",
          "sha256": "73b9e5076dbdea69dbce55b91f47bf492d0cfc7f586ca92b9342463ad14f943e",
          "sha1": "08f7045161cada2ede809e41a4db0f4752b2b146",
          "md5": "4c2928b9acbf3053fa357b7a3e7e2310"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "acl-1.1.11-SNAPSHOT-sources.jar",
          "url": "acl-1.1.11-SNAPSHOT-sources.jar",
          "size": 13374,
          "sha512": "0eec0f422794ec29160009cb280af07e3d42b458ae234699be1fdf8560d093a373454892b949820ac80da3bcbaffb4c7b0c7a3c98501b8cbbc6df8bf412936be",
          "sha256": "ac8e8ce8ec6d827d4ba75bc8374ab21ae8671d3e155ebf3b51062f7c94dd90da",
          "sha1": "f7a0e49dd763e051f5fb7499bf6251b7cb2c1d0e",
          "md5": "b9212c70612b65ee72d14581b5bd922a"
        }
      ]
    }
  ]
}
