{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "acl-core",
    "version": "1.0.75-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "acl-core-1.0.75-SNAPSHOT.jar",
          "url": "acl-core-1.0.75-SNAPSHOT.jar",
          "size": 21308,
          "sha512": "06ebc0590245dbc78ddc979044fef76eae35edb8ffb491390259505389d4b90707c644bbb909261ede11daa37fd875ab803872c82f1b3f0e5636b11782bfef9b",
          "sha256": "0b97c0fd12b71eb34e7f1f1de3dba3e3048227d8e160bf575a187176ddbfea93",
          "sha1": "62c70a85a1427ef1a45c883daa9caf079e80e10b",
          "md5": "0c3672a1f3bb8164cf87a1ea0d57cb88"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-loom",
          "version": {
            "requires": "1.4-SNAPSHOT"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.1.3-jre"
          }
        },
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.24"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "architectury-plugin",
          "module": "architectury-plugin.gradle.plugin",
          "version": {
            "requires": "3.4-SNAPSHOT"
          }
        },
        {
          "group": "com.github.johnrengelman",
          "module": "shadow",
          "version": {
            "requires": "8.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "acl-core-1.0.75-SNAPSHOT.jar",
          "url": "acl-core-1.0.75-SNAPSHOT.jar",
          "size": 21308,
          "sha512": "06ebc0590245dbc78ddc979044fef76eae35edb8ffb491390259505389d4b90707c644bbb909261ede11daa37fd875ab803872c82f1b3f0e5636b11782bfef9b",
          "sha256": "0b97c0fd12b71eb34e7f1f1de3dba3e3048227d8e160bf575a187176ddbfea93",
          "sha1": "62c70a85a1427ef1a45c883daa9caf079e80e10b",
          "md5": "0c3672a1f3bb8164cf87a1ea0d57cb88"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "acl-core-1.0.75-SNAPSHOT-sources.jar",
          "url": "acl-core-1.0.75-SNAPSHOT-sources.jar",
          "size": 11973,
          "sha512": "24f3249aad1baef597a91c01cef1810ab1aaa42ebe7a6775e0e7e4e0d8e646060a5067995e15aea0a029a8b313e4123e5ee0958ebdc9a1c2f9c4f56a0c69c7a4",
          "sha256": "8245e6c08218418f38b682302bf1a8fe6a7d523e25efc1e61accca23085b97f6",
          "sha1": "b1aa8f57a1d848265145ed0f83699f32bf60a599",
          "md5": "a0d34e8b957474da2f55ac21260e8a3e"
        }
      ]
    }
  ]
}
