{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "acl-core",
    "version": "1.0.75-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "acl-core-1.0.75-SNAPSHOT.jar",
          "url": "acl-core-1.0.75-SNAPSHOT.jar",
          "size": 21285,
          "sha512": "3d7b72d7a631fbb3c7429f3b32fedd269c3473470e2fbc7f049e08348c494157a6b0f38eed84162fbe256b3ba69518599f6f2fbec7fb4bd00ef81a4962305bcb",
          "sha256": "1da77075cfac33717b74e92731d3ad39192da641c3c936eddf7307d54f22e834",
          "sha1": "e97767cff4b5a5d83b5b994edb3dcdb09c6af517",
          "md5": "2ec2d673c2bd47ce4c4d86a28913229d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-loom",
          "version": {
            "requires": "1.4-SNAPSHOT"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.1.3-jre"
          }
        },
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.24"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "architectury-plugin",
          "module": "architectury-plugin.gradle.plugin",
          "version": {
            "requires": "3.4-SNAPSHOT"
          }
        },
        {
          "group": "com.github.johnrengelman",
          "module": "shadow",
          "version": {
            "requires": "8.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "acl-core-1.0.75-SNAPSHOT.jar",
          "url": "acl-core-1.0.75-SNAPSHOT.jar",
          "size": 21285,
          "sha512": "3d7b72d7a631fbb3c7429f3b32fedd269c3473470e2fbc7f049e08348c494157a6b0f38eed84162fbe256b3ba69518599f6f2fbec7fb4bd00ef81a4962305bcb",
          "sha256": "1da77075cfac33717b74e92731d3ad39192da641c3c936eddf7307d54f22e834",
          "sha1": "e97767cff4b5a5d83b5b994edb3dcdb09c6af517",
          "md5": "2ec2d673c2bd47ce4c4d86a28913229d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "acl-core-1.0.75-SNAPSHOT-sources.jar",
          "url": "acl-core-1.0.75-SNAPSHOT-sources.jar",
          "size": 11971,
          "sha512": "923d8e3fd4f3ea4aadc62316a9deb7b1d3ce3962d50a6c8e66623f4ad1a4ac39b0a24ecfadbb94f735b79054cd15e0001dc7842211a79cb4878e23cd976e881b",
          "sha256": "27ed65fb9ff6002f771aabf7ba609a2d2b2fa4a0f40ad53df2a59b6d447f7ff2",
          "sha1": "c7ca707021a14653cf9209b1e79e5e3db74379fe",
          "md5": "0766241a6c67b6ff3ad638b834635def"
        }
      ]
    }
  ]
}
