{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "acl-core",
    "version": "1.1.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "acl-core-1.1.4-SNAPSHOT.jar",
          "url": "acl-core-1.1.4-SNAPSHOT.jar",
          "size": 23737,
          "sha512": "b2d610f53f08dc7a856c412d6ed2b207e1c9736f8bfcd22238992194783e47760bd7873cf535fde92d92dd004619dec9b1cc9dd935ea302f3d66203d0732dcbd",
          "sha256": "c2681d90b111f38da0a6128fd0d11b8ef5fb5393e223bc0b329dacaeba2462b0",
          "sha1": "28728aeacb9c72ecb2b0ecf38766049766305727",
          "md5": "1bdf5207560a4d2f8d6d234d167e9242"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-loom",
          "version": {
            "requires": "1.4-SNAPSHOT"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.1.3-jre"
          }
        },
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.24"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "architectury-plugin",
          "module": "architectury-plugin.gradle.plugin",
          "version": {
            "requires": "3.4-SNAPSHOT"
          }
        },
        {
          "group": "com.github.johnrengelman",
          "module": "shadow",
          "version": {
            "requires": "8.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "acl-core-1.1.4-SNAPSHOT.jar",
          "url": "acl-core-1.1.4-SNAPSHOT.jar",
          "size": 23737,
          "sha512": "b2d610f53f08dc7a856c412d6ed2b207e1c9736f8bfcd22238992194783e47760bd7873cf535fde92d92dd004619dec9b1cc9dd935ea302f3d66203d0732dcbd",
          "sha256": "c2681d90b111f38da0a6128fd0d11b8ef5fb5393e223bc0b329dacaeba2462b0",
          "sha1": "28728aeacb9c72ecb2b0ecf38766049766305727",
          "md5": "1bdf5207560a4d2f8d6d234d167e9242"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "acl-core-1.1.4-SNAPSHOT-sources.jar",
          "url": "acl-core-1.1.4-SNAPSHOT-sources.jar",
          "size": 12689,
          "sha512": "7f59c10b1318b9625de15d0bcf9782f1dda76f968e4e87e9a2e058aa42d166afd2f3677a3bb275b8ad42702e1287fb4b330bb6d175a6cb3a614ef9afd62ba9aa",
          "sha256": "de782b9a2f0eb84dfd962ebbc16342a9b63ea0d44165c11a2b35dd60728d9dae",
          "sha1": "8ff05954cbf77368b6c2a111ff5089e71f0e8174",
          "md5": "9133f2fa156eb9e4f07f87be6e2e2791"
        }
      ]
    }
  ]
}
