{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "acl",
    "version": "1.1.16-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "acl-1.1.16-SNAPSHOT.jar",
          "url": "acl-1.1.16-SNAPSHOT.jar",
          "size": 28377,
          "sha512": "dfa65d43ec04ef8498c5d78107ed72c2f030c86ce0925ca39b655b1e051ddfd1e7aecec7bdbd127c2136197653909b0c2432537c9bea9ad9e51e3334f100b628",
          "sha256": "a42925a502b9514413a8cb99013bee5aa711f971d54bb126c435cca037196c55",
          "sha1": "65540b318349d68081a5bc9e2f29f412fb2c4e42",
          "md5": "3f7039f842ad93745c4e154cfef134c7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-loom",
          "version": {
            "requires": "1.4-SNAPSHOT"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.1.3-jre"
          }
        },
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.24"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "architectury-plugin",
          "module": "architectury-plugin.gradle.plugin",
          "version": {
            "requires": "3.4-SNAPSHOT"
          }
        },
        {
          "group": "com.github.johnrengelman",
          "module": "shadow",
          "version": {
            "requires": "8.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "acl-1.1.16-SNAPSHOT.jar",
          "url": "acl-1.1.16-SNAPSHOT.jar",
          "size": 28377,
          "sha512": "dfa65d43ec04ef8498c5d78107ed72c2f030c86ce0925ca39b655b1e051ddfd1e7aecec7bdbd127c2136197653909b0c2432537c9bea9ad9e51e3334f100b628",
          "sha256": "a42925a502b9514413a8cb99013bee5aa711f971d54bb126c435cca037196c55",
          "sha1": "65540b318349d68081a5bc9e2f29f412fb2c4e42",
          "md5": "3f7039f842ad93745c4e154cfef134c7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "acl-1.1.16-SNAPSHOT-sources.jar",
          "url": "acl-1.1.16-SNAPSHOT-sources.jar",
          "size": 13423,
          "sha512": "c265ea275690ab9f9f8cf3edce868e90aed444804ca438366bf602ae67c41ba5cc525120278f606a473feb14e512be4f54b0051e4738a73ef85762a3f8735eef",
          "sha256": "30e8452ff00d0407432790a66b0b6152d3e85f377d5b6f60688075fb2d944315",
          "sha1": "35e980168d9898009e2f4ddd4e548b2ae951ed77",
          "md5": "3026d990142b41b012555314a634f231"
        }
      ]
    }
  ]
}
