{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "acl",
    "version": "1.1.16-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "acl-1.1.16-SNAPSHOT.jar",
          "url": "acl-1.1.16-SNAPSHOT.jar",
          "size": 28364,
          "sha512": "9302445f3bc614675bcc17bad93648c105817cefba3f021fc82efd3fa7b6540aadc29cf4ba7bedafc7843e13ed25baf401a60577642234342aebd9b5c55a4ec9",
          "sha256": "6907c1e8067afa420d05947bc84934496e4ffb363e31d8e11d0b290c7111608d",
          "sha1": "118ae1f9867909c884b5431e746ca565429892b9",
          "md5": "90be0abba18dc9d31f4eebc6af8a8a05"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-loom",
          "version": {
            "requires": "1.4-SNAPSHOT"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.1.3-jre"
          }
        },
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.24"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "architectury-plugin",
          "module": "architectury-plugin.gradle.plugin",
          "version": {
            "requires": "3.4-SNAPSHOT"
          }
        },
        {
          "group": "com.github.johnrengelman",
          "module": "shadow",
          "version": {
            "requires": "8.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "acl-1.1.16-SNAPSHOT.jar",
          "url": "acl-1.1.16-SNAPSHOT.jar",
          "size": 28364,
          "sha512": "9302445f3bc614675bcc17bad93648c105817cefba3f021fc82efd3fa7b6540aadc29cf4ba7bedafc7843e13ed25baf401a60577642234342aebd9b5c55a4ec9",
          "sha256": "6907c1e8067afa420d05947bc84934496e4ffb363e31d8e11d0b290c7111608d",
          "sha1": "118ae1f9867909c884b5431e746ca565429892b9",
          "md5": "90be0abba18dc9d31f4eebc6af8a8a05"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "acl-1.1.16-SNAPSHOT-sources.jar",
          "url": "acl-1.1.16-SNAPSHOT-sources.jar",
          "size": 13417,
          "sha512": "41f0cedabeb745147331812ac684494bc5dd9ec06fd9a98b0c2593277d1142654cbae2211771aa2b83ac9137ca47d0b27421b935f4530faaef8f855d1e6e57e2",
          "sha256": "4907ca5856751df2ab928cc2ba0764fcd3544bdc883a43a78d45e67396e13cf1",
          "sha1": "13de564daa57c78326835e9e4443e0995c884546",
          "md5": "69a0d73c4cba13a589ee98c2e978fd45"
        }
      ]
    }
  ]
}
