{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "acl-core",
    "version": "1.1.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "acl-core-1.1.3-SNAPSHOT.jar",
          "url": "acl-core-1.1.3-SNAPSHOT.jar",
          "size": 22290,
          "sha512": "747401cc9b743a4e81f7e872fcb7491b5164a81a4a8aeea946a50e72aaca70c69c3c1ec9874ae34b54faf7c87d1131c2d670324f4a9864dcb0c1cc02fd4da167",
          "sha256": "e5fb7d1d197a1c92928cd492eed6d74bcb9d660b90e8febdfd77204639eeac27",
          "sha1": "e8cb3fb4082ca207126feda19e1420187c7d8a87",
          "md5": "edd307f8f1ccf894fa0ec19bfe4c29b1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-loom",
          "version": {
            "requires": "1.4-SNAPSHOT"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.1.3-jre"
          }
        },
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.24"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "architectury-plugin",
          "module": "architectury-plugin.gradle.plugin",
          "version": {
            "requires": "3.4-SNAPSHOT"
          }
        },
        {
          "group": "com.github.johnrengelman",
          "module": "shadow",
          "version": {
            "requires": "8.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "acl-core-1.1.3-SNAPSHOT.jar",
          "url": "acl-core-1.1.3-SNAPSHOT.jar",
          "size": 22290,
          "sha512": "747401cc9b743a4e81f7e872fcb7491b5164a81a4a8aeea946a50e72aaca70c69c3c1ec9874ae34b54faf7c87d1131c2d670324f4a9864dcb0c1cc02fd4da167",
          "sha256": "e5fb7d1d197a1c92928cd492eed6d74bcb9d660b90e8febdfd77204639eeac27",
          "sha1": "e8cb3fb4082ca207126feda19e1420187c7d8a87",
          "md5": "edd307f8f1ccf894fa0ec19bfe4c29b1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "acl-core-1.1.3-SNAPSHOT-sources.jar",
          "url": "acl-core-1.1.3-SNAPSHOT-sources.jar",
          "size": 12538,
          "sha512": "7f747dee6cd7b7c130625972dba1e3bf1d7bdc42d50edcbc58d589222d9906e193780fb1bd010e09854b8d58550efcbedb2a486420f39717ebe715d6b3b3c956",
          "sha256": "eaefb6f08622d8036a0ef6fea1f700a03b99a5218682261e06b4efd048d8d543",
          "sha1": "4f717f5cfbc62a897c59ad00602c4ba300fb6f09",
          "md5": "82ed72dafb9ddf7fc2109eff4d50cbcd"
        }
      ]
    }
  ]
}
