{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "acl",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "acl-1.2.0.jar",
          "url": "acl-1.2.0.jar",
          "size": 34169,
          "sha512": "2e7641a23cf2fbf2e4af7177a004d373137f085e8f8bcf435caf41f869769767498911894dbb35d7edb1a3252d96053f41a2bae2abddbc82ab31fd75eb91eaa9",
          "sha256": "f6982103340f2db03dd1929e6659145602f0147361a34d2d43b847caf0a41f97",
          "sha1": "6b441171be6fc61ddc9e2c58674773f2da72a0ad",
          "md5": "e5c5930523ce98d20413badda2b2eddb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-loom",
          "version": {
            "requires": "1.4-SNAPSHOT"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.1.3-jre"
          }
        },
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.25"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "architectury-plugin",
          "module": "architectury-plugin.gradle.plugin",
          "version": {
            "requires": "3.4-SNAPSHOT"
          }
        },
        {
          "group": "com.github.johnrengelman",
          "module": "shadow",
          "version": {
            "requires": "8.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "acl-1.2.0.jar",
          "url": "acl-1.2.0.jar",
          "size": 34169,
          "sha512": "2e7641a23cf2fbf2e4af7177a004d373137f085e8f8bcf435caf41f869769767498911894dbb35d7edb1a3252d96053f41a2bae2abddbc82ab31fd75eb91eaa9",
          "sha256": "f6982103340f2db03dd1929e6659145602f0147361a34d2d43b847caf0a41f97",
          "sha1": "6b441171be6fc61ddc9e2c58674773f2da72a0ad",
          "md5": "e5c5930523ce98d20413badda2b2eddb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "acl-1.2.0-sources.jar",
          "url": "acl-1.2.0-sources.jar",
          "size": 16543,
          "sha512": "ea9f93a97baf4957331a82aaee8d52977eefd6d189a604feb094e7031a88692af62a6fe5b2f2af9eb3a6cc81a52bfc7644fdcfab2dc13ddbada71387fdb16e55",
          "sha256": "0cc503989bfea9495d9ff7c60e134d3d19e4777a1da26a46fcdc3647896f76b5",
          "sha1": "ce83230be5825c64b4afd673df0fbd7f4b498193",
          "md5": "114725c02daa9ac6a742f6a4d2bfe976"
        }
      ]
    }
  ]
}
