{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "acl",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "acl-1.2.0.jar",
          "url": "acl-1.2.0.jar",
          "size": 34113,
          "sha512": "86447e79025074b7adec46f883c56cb3f05875a4f44ae88777347c48bf81a5d062ec292b65bc783d5e797a84a6b9ef827b1f784cfcca0cba4f53c5776da2f431",
          "sha256": "c42c14538072ccf69c8140b03b850bf16ca093e2510eb3beff25752744da0377",
          "sha1": "e0e097a2da5c0b72b88c9031a9ed89eb25da25d1",
          "md5": "4c2da207a915b25221f8810167b3eb4c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-loom",
          "version": {
            "requires": "1.4-SNAPSHOT"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.1.3-jre"
          }
        },
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.25"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "architectury-plugin",
          "module": "architectury-plugin.gradle.plugin",
          "version": {
            "requires": "3.4-SNAPSHOT"
          }
        },
        {
          "group": "com.github.johnrengelman",
          "module": "shadow",
          "version": {
            "requires": "8.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "acl-1.2.0.jar",
          "url": "acl-1.2.0.jar",
          "size": 34113,
          "sha512": "86447e79025074b7adec46f883c56cb3f05875a4f44ae88777347c48bf81a5d062ec292b65bc783d5e797a84a6b9ef827b1f784cfcca0cba4f53c5776da2f431",
          "sha256": "c42c14538072ccf69c8140b03b850bf16ca093e2510eb3beff25752744da0377",
          "sha1": "e0e097a2da5c0b72b88c9031a9ed89eb25da25d1",
          "md5": "4c2da207a915b25221f8810167b3eb4c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "acl-1.2.0-sources.jar",
          "url": "acl-1.2.0-sources.jar",
          "size": 16531,
          "sha512": "2e74e206eb3284b7c9040f477f66f951b0b0bc54dc45cf9951a086607cf7caf1afde332e16fd7917445c06b6f5260a636092f64651c3331305a3d23478eead07",
          "sha256": "09910a8990a7570ab3292aaff36370ef8a955c8c5c3aada6a3ca9e3bfe4a3e15",
          "sha1": "a4193f1af4dca38fb53f708e5a0aab83a54534c5",
          "md5": "85f66b64d72f5c0650cde712904c0111"
        }
      ]
    }
  ]
}
