{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "acl",
    "version": "1.1.9-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "acl-1.1.9-SNAPSHOT.jar",
          "url": "acl-1.1.9-SNAPSHOT.jar",
          "size": 26010,
          "sha512": "5fe5efb93606a25adc3cb26ee2f2235eb98cfe82982dde7745fdaac8a144f82452ef77ebc9b964db1be5b54e6b5e548568bac39d1b4714bebe31faba504fc52f",
          "sha256": "84292bae65832daf72c38faa6e3ae77c05e1d9fa0a9e78d6c1071dfac2c7f5db",
          "sha1": "8121c50a2ddbee369eb7170d78c320d9fc214db2",
          "md5": "24b3075b16d14d8f016b12a031c09efa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-loom",
          "version": {
            "requires": "1.4-SNAPSHOT"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.1.3-jre"
          }
        },
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.24"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "architectury-plugin",
          "module": "architectury-plugin.gradle.plugin",
          "version": {
            "requires": "3.4-SNAPSHOT"
          }
        },
        {
          "group": "com.github.johnrengelman",
          "module": "shadow",
          "version": {
            "requires": "8.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "acl-1.1.9-SNAPSHOT.jar",
          "url": "acl-1.1.9-SNAPSHOT.jar",
          "size": 26010,
          "sha512": "5fe5efb93606a25adc3cb26ee2f2235eb98cfe82982dde7745fdaac8a144f82452ef77ebc9b964db1be5b54e6b5e548568bac39d1b4714bebe31faba504fc52f",
          "sha256": "84292bae65832daf72c38faa6e3ae77c05e1d9fa0a9e78d6c1071dfac2c7f5db",
          "sha1": "8121c50a2ddbee369eb7170d78c320d9fc214db2",
          "md5": "24b3075b16d14d8f016b12a031c09efa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "acl-1.1.9-SNAPSHOT-sources.jar",
          "url": "acl-1.1.9-SNAPSHOT-sources.jar",
          "size": 13329,
          "sha512": "391dcd263995dc3779a92bc6bee1ef86318fc4a1a456a95d6ad70d4896a24e66f5a8839ab53a1fc76b955c70df4a559dc4bcb3fcb416d70820b16cde8d74ccf2",
          "sha256": "55beab70c3719090e7f6a0d0ca3d25ec3074a5f7c18c01d43d7810a675b38bce",
          "sha1": "edf79b0369bea202cee54b696bbc87721f7a41e4",
          "md5": "bcb5837034366ef35237574a7fb17d50"
        }
      ]
    }
  ]
}
