{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.xenfork",
    "module": "acl",
    "version": "1.1.18-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "acl-1.1.18-SNAPSHOT.jar",
          "url": "acl-1.1.18-SNAPSHOT.jar",
          "size": 28302,
          "sha512": "9c780848a710ea5bb303e954a43a50c400e917843328e2e8f711b64df61655e046c0343740e406be1607d16df3018e226d3d3147242ba22b64352dd5b256ddbd",
          "sha256": "3f23654b5b0ea44c6bcdc36d9ff6f92061b1ed6435beb3fb7b5bd3ed4c7b7e33",
          "sha1": "a550b10e3a7fb233a56160bf01dbb1d6e4492eda",
          "md5": "6391fa8c7afabe80fb26f08e6308310a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-loom",
          "version": {
            "requires": "1.4-SNAPSHOT"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.1.3-jre"
          }
        },
        {
          "group": "cn.hutool",
          "module": "hutool-all",
          "version": {
            "requires": "5.8.24"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "architectury-plugin",
          "module": "architectury-plugin.gradle.plugin",
          "version": {
            "requires": "3.4-SNAPSHOT"
          }
        },
        {
          "group": "com.github.johnrengelman",
          "module": "shadow",
          "version": {
            "requires": "8.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "acl-1.1.18-SNAPSHOT.jar",
          "url": "acl-1.1.18-SNAPSHOT.jar",
          "size": 28302,
          "sha512": "9c780848a710ea5bb303e954a43a50c400e917843328e2e8f711b64df61655e046c0343740e406be1607d16df3018e226d3d3147242ba22b64352dd5b256ddbd",
          "sha256": "3f23654b5b0ea44c6bcdc36d9ff6f92061b1ed6435beb3fb7b5bd3ed4c7b7e33",
          "sha1": "a550b10e3a7fb233a56160bf01dbb1d6e4492eda",
          "md5": "6391fa8c7afabe80fb26f08e6308310a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "acl-1.1.18-SNAPSHOT-sources.jar",
          "url": "acl-1.1.18-SNAPSHOT-sources.jar",
          "size": 13406,
          "sha512": "a803f5b15705d2ab649eeb8a80f251b15d1939a516c6cbc34443177ba090bc2088470bba857d53b46b1d3070c2075c5652a65c8f668bc3954e2be6ba3d7c5285",
          "sha256": "8d0fac24db25ad2c48b968f800d5b8112af05a9db512d14aa1345b5469e3034e",
          "sha1": "05366233c2caecbae0be562f13d47e6a3c1e1fbc",
          "md5": "65a55458f8cea3917e0018b6864fef55"
        }
      ]
    }
  ]
}
